### ISSUE TITLE
Node warnings

### ISSUE THREAD

**Issue by crisbeto** [anton164/grunt-fixindent#1]
When using the Grunt task I get this error:

```
(node) warning: Recursive process.nextTick detected. This will break in the next
 version of node. Please use setImmediate for recursive deferral.

node.js:0
// Copyright Joyent, Inc. and other Node contributors.
^
RangeError: Maximum call stack size exceeded
```

Here's what my config looks like:

``` javascript
indent: {
    scripts: {
        src: [
            'js/**/*.js'
        ],
        dest: 'dist/',
        options: {
            style: 'space',
            size: 4
        }
    }
}
```

**Comment by anton164** [comment]
Hey @crisbeto, thanks for reporting the issue. Some of the 'indent' occurrences weren't correctly replaced with 'fixindent', so I'm guessing there was a conflict.

Install v0.1.3 and try this config file and it should hopefully work (renamed task from **indent** to **fixindent**):

``` javascript
fixindent: {
    scripts: {
        src: [
            'js/**/*.js'
        ],
        dest: 'dist/',
        options: {
            style: 'space',
            size: 4
        }
    }
}
```

**Comment by anton164** [comment]
Oh there's a more likely possibility that you had the following in your gruntfile:
`grunt.registerTask('indent', ['indent', 'someothertask', ...]);`
When you register a task it should have a unique name, so with v0.1.3, this would work:
`grunt.registerTask('anynamenotliketask', ['fixindent', '...']);`

See http://gruntjs.com/frequently-asked-questions#why-am-i-getting-a-maximum-call-stack-size-exceeded-error

**Comment by crisbeto** [comment]
Yes, that was it.
